FCHyperNet: &FCHyperNet
  name: FCHyperNet
  in_dim: 120
  hidden_dim: 512
  out_dim: 512
  num_layers: 8
  linear_cfg:
    name: SNLinear
  act_cfg:
    name: LeakyReLU
    negative_slope: 0.01

CLN:
  in_dim: 256
  c_dim: 128
  linear_cfg:
    name: SNLinear

INRBlock: &INRBlock
  name: INRBlock
  in_features: 256
  out_features: 512
  c_dim: 128
  norm_cfg:
    name: CLN
    linear_cfg:
      name: SNLinear
  act_cfg:
    name: LeakyReLU
    negative_slope: 0.01
  linear_cfg:
    name: SNLinear

inrGAN_Generator128:
  hyper_net_cfg:
    name: FCHyperNet
    in_dim: 128
    hidden_dim: null
    out_dim: null
    num_layers: 8
    linear_cfg:
      name: SNLinear
    act_cfg:
      name: LeakyReLU
      negative_slope: 0.01
  inr_block_cfg:
    name: INRBlock
    c_dim: 256
    norm_cfg:
      name: CLN
      linear_cfg:
        name: SNLinear
    act_cfg:
      name: LeakyReLU
      negative_slope: 0.01
    linear_cfg:
      name: SNLinear
  in_channels: [4, 256, 512, 1024, 2048, ]
  out_channels: [256, 512, 1024, 2048, 2048, ]
  num_classes: 1000
  embedding_dim: 128
  w_dim: 128
  out_layer_cfg:
    name: SNLinear
    out_features: 3
  img_size: [128, 128]

  G_lr: 0.0001
  G_init: 'ortho'
  Generator:
    weight_decay: 0.001

Generator128_fit_oneimage:
  base: inrGAN_Generator128
  hyper_net_cfg:
    num_layers: 1
  in_channels: [4, 256, ]
  out_channels: [256, 512, ]
  img_path: "datasets/snail.jpg"
  num_classes: 1
  num_iter: 200000
  G_lr: 0.0001
  Generator:
    weight_decay: 0.0001


