train_ImageNet128:
  args:
    dataset: I128_hdf5
    data_root: "datasets/ImageNet_hdf5/ILSVRC128.hdf5"
    num_workers: 8
    batch_size: 256
    num_G_accumulations: 1
    num_D_accumulations: 1
    num_D_steps: 1
    G_lr: 1e-4
    D_lr: 4e-4
    D_B2: 0.999
    G_B2: 0.999
    G_attn: '64'
    D_attn: '64'
    G_nl: inplace_relu
    D_nl: inplace_relu
    SN_eps: 1e-6
    BN_eps: 1e-5
    adam_eps: 1e-6
    G_ortho: 0.0
    G_shared: true
    G_init: ortho
    D_init: ortho
    hier: true
    dim_z: 120
    shared_dim: 128
    G_eval_mode: true
    G_ch: 96
    D_ch: 96
    ema: true
    use_ema: true
    ema_start: 20000
    test_every: 2000
    save_every: 1000
    num_best_copies: 4
    num_save_copies: 2
    seed: 0
    use_multiepoch_sampler: true
    experiment_name: exp
    model: exp.omniGAN.BigGAN_omni
    which_train_fn: exp.omniGAN.train_fns
  Discriminator:
    output_dim: 1002
    weight_decay: 0.00001
  Generator:
    weight_decay: 0.001
  omni_loss:
    mode: p_and_n
    gamma: 1.0
    margin: 0.0
  inception_file: "datasets/ImageNet_hdf5/\
      I128_inception_moments.npz"
  root_obs: "s3://bucket-7001/ZhouPeng"
  modelarts_download:
    data_root:
      datapath_obs: "{global_cfg.root_obs}/keras/\
        ImageNet_hdf5/ILSVRC128.hdf5"
      datapath: "{global_cfg.data_root}"
      overwrite: false
      eval: true
    inception_file:
      datapath_obs: "{global_cfg.root_obs}/keras/\
      ImageNet_hdf5/I128_inception_moments.npz"
      datapath: "{global_cfg.inception_file}"
      overwrite: false
      eval: true
    inceptionv3:
      datapath_obs: "{global_cfg.root_obs}/keras/Omni-GAN-ImageNet/\
              datasets/inception_v3_google-1a9a5a14.pth"
      datapath: '~/.cache/torch/hub/checkpoints/inception_v3_google-1a9a5a14.pth'
      overwrite: false
      eval: true

eval_ImageNet128:
  base: train_ImageNet128
  evaluation:
    eval: true
#    G_ema_best_IS0: IS=190.184 FID=8.4797
#    G_ema_best_IS1: IS=166.883 FID=9.2977
#    G_ema_best_IS2: IS=190.878 FID=8.4731
#    G_ema_best_IS3: IS=191.017 FID=8.5999
    G_ema_model: "datasets/omniGAN128_20201220_173111_408/\
          G_ema_best_IS0.pth"
#      G_ema_best_IS3.pth"
#    G_ema_best_FID0: IS=185.678 FID=8.3130
#    G_ema_best_FID1: IS=190.184 FID=8.4820
#    G_ema_best_FID2: IS=160.275 FID=9.4162
#    G_ema_best_FID3: IS=175.686 FID=8.7097
#    G_ema_model: "datasets/omniGAN128_20201220_173111_408/\
#          G_ema_best_FID0.pth"



train_ch64_ImageNet128:
  base: train_ImageNet128
  args:
    G_ch: 64
    D_ch: 64
    batch_size: 256
    num_G_accumulations: 1
    num_D_accumulations: 1
    num_D_steps: 4


_build_omnigan_generator_128: &_build_omnigan_generator_128
  register_modules:
    - exp.omniGAN.models.OmniGAN
  name: exp.omniGAN.models.OmniGAN.Generator
  G_ch: 96
  dim_z: 120
  bottom_width: 4
  resolution: 128
  G_kernel_size: 3
  G_attn: '64'
  n_classes: 1000
  G_shared: true
  shared_dim: 128
  hier: true
  cross_replica: false
  mybn: false
  G_init: 'ortho'
  G_param: 'SN'
  norm_style: 'bn'
  BN_eps: 1.e-5
  SN_eps: 1.e-6
  G_fp16: false
  G_lr: 1.e-4
  G_B1: 0.
  G_B2: 0.999
  weight_decay: 0.001
  adam_eps: 1.e-6
  skip_init: false
  no_optim: false

_build_omnigan_discriminator_128: &_build_omnigan_discriminator_128
  register_modules:
    - exp.omniGAN.models.OmniGAN
  name: exp.omniGAN.models.OmniGAN.Discriminator
  D_ch: 96
  D_wide: true
  resolution: 128
  D_kernel_size: 3
  D_attn: '64'
  n_classes: 1000
  D_init: 'ortho'
  D_param: 'SN'
  SN_eps: 1.e-6
  D_fp16: false
  D_lr: 4.e-4
  D_B1: 0.
  D_B2: 0.999
  weight_decay: 0.00001
  adam_eps: 1.e-6
  output_dim: 1002

train_ImageNet128_build_net:
  args:
    dataset: I128_hdf5
    data_root: "datasets/ImageNet_hdf5/ILSVRC128.hdf5"
    num_workers: 8
    batch_size: 256
    num_G_accumulations: 1
    num_D_accumulations: 1
    num_D_steps: 1
    G_lr: 1e-4
    D_lr: 4e-4
    D_B2: 0.999
    G_B2: 0.999
    G_attn: '64'
    D_attn: '64'
    G_nl: inplace_relu
    D_nl: inplace_relu
    SN_eps: 1e-6
    BN_eps: 1e-5
    adam_eps: 1e-6
    G_ortho: 0.0
    G_shared: true
    G_init: ortho
    D_init: ortho
    hier: true
    dim_z: 120
    shared_dim: 128
    G_eval_mode: true
    G_ch: 96
    D_ch: 96
    ema: true
    use_ema: true
    ema_start: 20000
    test_every: 2000
    save_every: 1000
    num_best_copies: 4
    num_save_copies: 2
    seed: 0
    use_multiepoch_sampler: true
    experiment_name: exp
    model: exp.omniGAN.BigGAN_omni
    which_train_fn: exp.omniGAN.train_fns
  Generator: *_build_omnigan_generator_128
  Discriminator: *_build_omnigan_discriminator_128

  omni_loss:
    mode: p_and_n
    gamma: 1.0
    margin: 0.0
  inception_file: "datasets/ImageNet_hdf5/\
      I128_inception_moments.npz"
  root_obs: "s3://bucket-7001/ZhouPeng"
  modelarts_download:
    data_root:
      datapath_obs: "{global_cfg.root_obs}/keras/\
        ImageNet_hdf5/ILSVRC128.hdf5"
      datapath: "{global_cfg.data_root}"
      overwrite: false
      eval: true
    inception_file:
      datapath_obs: "{global_cfg.root_obs}/keras/\
      ImageNet_hdf5/I128_inception_moments.npz"
      datapath: "{global_cfg.inception_file}"
      overwrite: false
      eval: true
    inceptionv3:
      datapath_obs: "{global_cfg.root_obs}/keras/Omni-GAN-ImageNet/\
              datasets/inception_v3_google-1a9a5a14.pth"
      datapath: '~/.cache/torch/hub/checkpoints/inception_v3_google-1a9a5a14.pth'
      overwrite: false
      eval: true

eval_ImageNet128_build_net:
  base: train_ImageNet128_build_net
  evaluation:
    eval: true
#    G_ema_best_IS0: IS=190.184 FID=8.4820
#    G_ema_best_IS1: IS=166.883 FID=9.2989
#    G_ema_best_IS2: IS=190.878 FID=8.4731
#    G_ema_best_IS3: IS=191.017 FID=8.5999
    G_ema_model: "datasets/omniGAN128_20201220_173111_408/exp/\
          G_ema_best_IS0.pth"
#      G_ema_best_IS3.pth"
#    G_ema_best_FID0: IS=185.678 FID=8.3142
#    G_ema_best_FID1: IS=190.184 FID=8.4820
#    G_ema_best_FID2: IS=160.275 FID=9.4156
#    G_ema_best_FID3: IS=175.686 FID=8.7108
#    G_ema_model: "datasets/omniGAN128_20201220_173111_408/exp/\
#          G_ema_best_FID0.pth"

eval_ImageNet128_build_net_val:
  base: train_ImageNet128_build_net
  inception_file: datasets/ImageNet_hdf5/I128_val_inception_moments.npz
  evaluation:
    eval: true
#    G_ema_best_IS0: IS=190.184 FID=9.2054
#    G_ema_best_IS1: IS=166.883 FID=9.8630
#    G_ema_best_IS2: IS=190.878 FID=9.2335
#    G_ema_best_IS3: IS=191.017 FID=9.3537
    G_ema_model: "datasets/omniGAN128_20201220_173111_408/exp/\
          G_ema_best_IS0.pth"
#      G_ema_best_IS3.pth"
#    G_ema_best_FID0: IS=185.678 FID=8.9325
#    G_ema_best_FID1: IS=190.184 FID=9.2054
#    G_ema_best_FID2: IS=160.275 FID=9.9015
#    G_ema_best_FID3: IS=175.686 FID=9.2735
#    G_ema_model: "datasets/omniGAN128_20201220_173111_408/exp/\
#          G_ema_best_FID0.pth"

eval_truncation_ImageNet128:
  Generator: *_build_omnigan_generator_128
  args:
    batch_size: 256
    accumulate_stats: true
  weights_root: "datasets/omniGAN128_20201220_173111_408/"
  pretrained_model: "datasets/omniGAN128_20201220_173111_408/exp/\
    G_ema_best_FID0.pth"
  inception_file: datasets/ImageNet_hdf5/I128_inception_moments.npz

