Generator128:
  dim_z: 120
  n_classes: 1000
  G_shared: true
  shared_dim: 128
  hier: true
  bottom_width: 8
  channel: 3
  use_sn: true
  num_heads:
    - 1
    - 1
    - 2
    - 4
  block_repeat:
    - 10
    - 10
    - 10
    - 9
  ff_dim_mul: 4
  dropout: 0.
  weight_decay: 0.001


Block:
  in_dim: 3
  out_dim: 12
  num_heads: 1
  ff_dim: 48
  dropout: 0.
  use_sn: true


Generator128_fit_oneimage:
  base: Generator128
  img_path: "datasets/snail.jpg"
  n_classes: 1
  num_iter: 200000
  weight_decay: 0.0001
  block_repeat:
    - 1
    - 1
    - 1
    - 1