calculate_fid_stat_CIFAR10:
  register_modules:
    - "template_lib.d2.data.build_cifar10"
  run_func: "TFFIDISScore.test_case_calculate_fid_stat_CIFAR10()"
  dataset_name: "cifar10_train"
  IMS_PER_BATCH: 32
  img_size: 32
  DATALOADER:
    NUM_WORKERS: 0
  dataset_mapper_cfg:
    name: CIFAR10DatasetMapper
  OUTPUT_DIR: 'results'
  GAN_metric:
    name: TFFIDISScore
    tf_fid_stat: "datasets/tf_fid_stat/fid_stats_tf_cifar10_train_32.npz"
    tf_inception_model_dir: "datasets/tf_inception_model"
    num_inception_images: 50000


calculate_fid_stat_CIFAR100:
  register_modules:
    - "template_lib.d2.data.build_cifar100"
  dataset_name: "cifar100_train"
  IMS_PER_BATCH: 32
  img_size: 32
  DATALOADER:
    NUM_WORKERS: 0
  dataset_mapper_cfg:
    name: CIFAR100DatasetMapper
  OUTPUT_DIR: 'results'
  GAN_metric:
    name: TFFIDISScore
    tf_fid_stat: "datasets/tf_fid_stat/fid_stats_tf_cifar100_train_32.npz"
    tf_inception_model_dir: "datasets/tf_inception_model"
    num_inception_images: 50000


