train_ImageNet128:
  args:
    dataset: I128_hdf5
    data_root: datasets/ImageNet_hdf5/ILSVRC128.hdf5
    parallel: true
    shuffle: true
    num_workers: 8
    batch_size: 256
    num_G_accumulations: 1
    num_D_accumulations: 1
    num_D_steps: 1
    G_lr: 1e-4
    D_lr: 4e-4
    D_B2: 0.999
    G_B2: 0.999
    G_attn: '64'
    D_attn: '64'
    G_nl: inplace_relu
    D_nl: inplace_relu
    SN_eps: 1e-6
    BN_eps: 1e-5
    adam_eps: 1e-6
    G_ortho: 0.0
    G_shared: true
    G_init: ortho
    D_init: ortho
    hier: true
    dim_z: 120
    shared_dim: 128
    G_eval_mode: true
    G_ch: 96
    D_ch: 96
    ema: true
    use_ema: true
    ema_start: 20000
    test_every: 2000
    save_every: 1000
    num_best_copies: 4
    num_save_copies: 2
    seed: 0
    use_multiepoch_sampler: true
    experiment_name: exp
    model: exp.omniGAN.BigGAN_omni
    which_train_fn: exp.omniGAN.train_fns
  Discriminator:
    output_dim: 1002
    weight_decay: 1.0e-05
  Generator:
    weight_decay: 0.001
  omni_loss:
    mode: p_and_n
    gamma: 1.0
    margin: 0.0
  inception_file: datasets/ImageNet_hdf5/I128_inception_moments.npz

eval_ImageNet128:
  base: train_ImageNet128
  inception_file: "datasets/ImageNet_hdf5/I128_inception_moments.npz"
  evaluation:
    eval: true
    G_ema_model: "datasets/pretrained/omnigan_r128_G_ema.pth"

